version: '3'

services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:6.0.4-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/chat'
      - 'gems:/gems'

volumes:
  redis:
  postgres:
  gems: